[package]
name = "chess-rs"
version = "0.1.0"
authors = ["gan74"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
indicatif = "0.14.0"

[profile.release]
opt-level = 3